### ISSUE TITLE
roc and auc

### ISSUE THREAD

**Issue by wcornwell** [bobdouma/kappa_multinomial#2]
AUC.multiclass: no visible global function definition for ‘roc’
AUC.multiclass: no visible global function definition for ‘auc’

getting these errors when I run package checks

**Comment by bobdouma** [comment]
Those are dependent on package pROC. We could remove AUC.multiclass, although I am not aware of any other package that has this function..

**Comment by wcornwell** [comment]
I'll add pROC to the imports in the description file.  should be OK

**Comment by wcornwell** [comment]
turns out it needed to be in "suggests" and call the function as  pROC::roc and pROC::auc 

working now.

**Comment by bobdouma** [comment]
Where did you change this? Can’t see it in the file mAUC.r

**Comment by wcornwell** [comment]
check de0354f7fab7ada13323f444bf457fe53b978118
